server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

#basename : messages는 우리가 사용할 다국어 파일 이름이 messages라는 것이다
spring:
  message:
    basename: messages
  security:
    user:
      name: kcj3054
      password: 134679

management:
  endpoints:
    web:
      exposure:
        include: "*"